name: Docker Metadata Extraction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Defining variables for the job
    env:
      DOCKER_USERNAME:mjavan
      DOCKER_PASSWORD:  dckr_pat_ITLXcdMWVpfwqqX8pK6agWbJDEon
                                                              # If you're not concerned about this being exposed

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub using vars for credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      name: Docker Metadata Extraction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Defining variables for the job
    env:
      DOCKER_USERNAME:mjavan
      DOCKER_PASSWORD:  dckr_pat_ITLXcdMWVpfwqqX8pK6agWbJDEon
                                                              # If you're not concerned about this being exposed

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub using vars for credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
     name: Docker Metadata Extraction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Defining variables for the job
    env:
      DOCKER_USERNAME:mjavan
      DOCKER_PASSWORD:  dckr_pat_ITLXcdMWVpfwqqX8pK6agWbJDEon
                                                              # If you're not concerned about this being exposed

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub using vars for credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      # Extract Docker image metadat
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/my-image

      # Example step to print metadata (optional)
      - name: Print metadata
        run: echo "Image metadata: ${{ steps.meta.outputs.metadata }}"
