name: Docker Metadata Extraction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Defining variables for the job
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
                                                             

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub using vars for credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      # Docker Metadata Extraction
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/my-image
      
      # Example step to print all meta data
      - name: Debug metadata outputs
        run: echo "Available outputs: ${{ toJson(steps.meta.outputs) }}"
      
      # Example build and push the image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }} # Only push if the event is not a pull request
          tags: ${{ steps.meta.outputs.tags }} # Use the metadata tags for the image
          annotations: ${{ steps.meta.outputs.annotations }}
